[package]
name = "citrea-risc0-adapter"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
description = "An adapter allowing Citrea to use risc0 proving system"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
bincode = { workspace = true }
bonsai-sdk = { workspace = true, optional = true }
borsh = { workspace = true }
hex = { workspace = true }
metrics = { workspace = true, optional = true }
risc0-zkvm = { workspace = true, default-features = false, features = ["std"] }
serde = { workspace = true }
sov-db = { path = "../sovereign-sdk/full-node/db/sov-db", optional = true }
sov-rollup-interface = { path = "../sovereign-sdk/rollup-interface" }
tracing = { workspace = true }

[features]
default = []
native = [
  "dep:bonsai-sdk",
  "dep:sov-db",
  "dep:metrics",
  "risc0-zkvm/prove",
  "sov-rollup-interface/native",
]
bench = ["native"]
