name: 'Install risc0'
description: 'Installs risc0 toolchain'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true

runs:
  using: "composite"
  steps:
    - name: Install risc0
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      run: | 
        curl -L https://risczero.com/install | bash
        export PATH="$PATH:$HOME/.risc0/bin"
        rzup install r0vm 2.0.2
        rzup install cargo-risczero 2.0.2
        rzup install cpp
        rzup install rust 1.85.0
        rzup default r0vm 2.0.2
        rzup default cargo-risczero 2.0.2
        rzup default rust 1.85.0
