name: PR Title Check

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review

jobs:
  validate:
    name: Validate PR Title
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Check PR Title
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            docs
            style
            refactor
            perf
            test
            build
            ci
            chore
            revert
          
          scopes: |
          requireScope: false
          subjectPatternError: |
            The subject "{subject}" found in the pull request title "{title}"
            didn't match the configured pattern. Please ensure that:
            - The subject starts with a lowercase letter
            - The subject doesn't end with a period
            
            Example of a valid PR title:
            feat: add new mempool maintenance feature
            fix(sequencer): resolve memory leak in transaction processing
          
          validateSingleCommit: false
          validateSingleCommitMatchesPrTitle: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
